#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc config automatic_scheme spiral
bspc config border_width 2
bspc config border_width 0
bspc config window_gap 5

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
#bspc rule -a Kitty   state=floating layer=above

polybar bar &
